package com.bobmowzie.mowziesmobs.client.model.entity;

import com.bobmowzie.mowziesmobs.client.model.tools.AdvancedModelRenderer;
import com.bobmowzie.mowziesmobs.client.model.tools.MowzieModelBase;
import com.bobmowzie.mowziesmobs.client.model.tools.MowzieModelRenderer;
import com.bobmowzie.mowziesmobs.common.entity.EntityTribeElite;
import com.bobmowzie.mowziesmobs.common.entity.EntityTribesman;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;
import thehippomaster.AnimationAPI.AnimationAPI;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelTribesman extends MowzieModelBase {
    public MowzieModelRenderer modelCore;
    public AdvancedModelRenderer body;
    public MowzieModelRenderer chest;
    public MowzieModelRenderer thighLeft;
    public MowzieModelRenderer thighRight;
    public MowzieModelRenderer loinClothFront;
    public MowzieModelRenderer loinClothBack;
    public MowzieModelRenderer armRightJoint;
    public MowzieModelRenderer armLeftJoint;
    public MowzieModelRenderer neckJoint;
    public MowzieModelRenderer armUpperRight;
    public MowzieModelRenderer armLowerRight;
    public MowzieModelRenderer handRight;
    public AdvancedModelRenderer spearBase;
    public AdvancedModelRenderer spear;
    public MowzieModelRenderer armUpperLeft;
    public MowzieModelRenderer armLowerLeft;
    public MowzieModelRenderer handLeft;
    public MowzieModelRenderer shieldBase;
    public MowzieModelRenderer shield;
    public MowzieModelRenderer neck;
    public MowzieModelRenderer headJoint;
    public MowzieModelRenderer head;
    public AdvancedModelRenderer maskBase;
    public MowzieModelRenderer earLeft;
    public MowzieModelRenderer earRight;
    public MowzieModelRenderer maskLeft;
    public MowzieModelRenderer maskRight;
    public AdvancedModelRenderer mane;
    public MowzieModelRenderer earringLeft;
    public MowzieModelRenderer earringRight;
    public MowzieModelRenderer calfLeft;
    public MowzieModelRenderer footLeft;
    public MowzieModelRenderer calfRight;
    public MowzieModelRenderer footRight;
    public MowzieModelRenderer thighLeftJoint;
    public MowzieModelRenderer thighRightJoint;
    public MowzieModelRenderer scaler;
    public MowzieModelRenderer flailer;

    private Animator animator;

    public ModelTribesman() {
        animator = new Animator(this);
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.footLeft = new MowzieModelRenderer(this, 21, 53);
        this.footLeft.setRotationPoint(0.0F, 5.5F, 0.0F);
        this.footLeft.addBox(-2.5F, 0.5F, -7.0F, 5, 2, 9, 0.0F);
        this.setRotateAngle(footLeft, -0.5235987755982988F, 0.0F, 0.0F);
        this.thighLeft = new MowzieModelRenderer(this, 41, 52);
        this.thighLeft.mirror = true;
        this.thighLeft.setRotationPoint(0, 0, 0);
        this.thighLeft.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2, 0.0F);
        this.setRotateAngle(thighLeft, -0.7853981633974483F, -0.6981317007977318F, 0.0F);
        this.thighLeftJoint = new MowzieModelRenderer(this, 41, 52);
        this.thighLeftJoint.mirror = true;
        this.thighLeftJoint.setRotationPoint(4.0F, 0.0F, 0.0F);
        this.thighLeftJoint.addBox(0, 0, 0, 0, 0, 0, 0.0F);
        this.setRotateAngle(thighLeftJoint, 0, 0, 0.0F);
        this.spearBase = new AdvancedModelRenderer(this, 0, 0);
        this.spearBase.setRotationPoint(0.0F, 3.0F, 0.0F);
        this.spearBase.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.loinClothBack = new MowzieModelRenderer(this, 32, 27);
        this.loinClothBack.setRotationPoint(0.0F, 2.0F, 2.0F);
        this.loinClothBack.addBox(-4.0F, 0.0F, 0.0F, 8, 7, 0, 0.0F);
        this.setRotateAngle(loinClothBack, 0.17453292519943295F, 0.0F, 0.0F);
        this.loinClothFront = new MowzieModelRenderer(this, 32, 27);
        this.loinClothFront.setRotationPoint(0.0F, 2.0F, -6.0F);
        this.loinClothFront.addBox(-4.0F, 0.0F, 0.0F, 8, 7, 0, 0.0F);
        this.setRotateAngle(loinClothFront, -0.17453292519943295F, 0.0F, 0.0F);
        this.thighRight = new MowzieModelRenderer(this, 41, 52);
        this.thighRight.setRotationPoint(0, 0, 0);
        this.thighRight.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2, 0.0F);
        this.setRotateAngle(thighRight, -0.7853981633974483F, 0.6981317007977318F, 0.0F);
        this.thighRightJoint = new MowzieModelRenderer(this, 41, 52);
        this.thighRightJoint.setRotationPoint(-4.0F, 0.0F, 0.0F);
        this.thighRightJoint.addBox(0, 0, 0, 0, 0, 0, 0.0F);
        this.setRotateAngle(thighRightJoint, 0, 0, 0);
        this.armLowerLeft = new MowzieModelRenderer(this, 12, 55);
        this.armLowerLeft.mirror = true;
        this.armLowerLeft.setRotationPoint(0.0F, 8.0F, 0.0F);
        this.armLowerLeft.addBox(-1.0F, 0.0F, -1.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(armLowerLeft, -1.0471975511965976F, 0.0F, 0.0F);
        this.armLowerRight = new MowzieModelRenderer(this, 12, 55);
        this.armLowerRight.setRotationPoint(0.0F, 8.0F, 0.0F);
        this.armLowerRight.addBox(-1.0F, 0.0F, -1.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(armLowerRight, -1.0471975511965976F, 0.0F, 0.0F);
        this.earringRight = new MowzieModelRenderer(this, 0, 29);
        this.earringRight.setRotationPoint(-3.0F, 4.0F, 0.5F);
        this.earringRight.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 0, 0.0F);
        this.neckJoint = new MowzieModelRenderer(this, 0, 0);
        this.neckJoint.setRotationPoint(0.0F, -4.0F, 1.0F);
        this.neckJoint.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(neckJoint, 0.3490658503988659F, 0.0F, 0.0F);
        this.armUpperLeft = new MowzieModelRenderer(this, 41, 52);
        this.armUpperLeft.mirror = true;
        this.armUpperLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.armUpperLeft.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2, 0.0F);
        this.setRotateAngle(armUpperLeft, 0.0F, 0.0F, -0.9599310885968813F);
        this.spear = new AdvancedModelRenderer(this, 66, 0);
        this.spear.setRotationPoint(0.0F, 0.0F, 0.0F);
        spear.add3DTexture(-4, -4, 0.5F, 15, 15);
        this.setRotateAngle(spear, 2.356194490192345F, 0.0F, 3.141592653589793F);
        this.earLeft = new MowzieModelRenderer(this, 48, 0);
        this.earLeft.setRotationPoint(4.0F, -4.0F, -3.0F);
        this.earLeft.addBox(0.0F, -2.0F, 0.0F, 4, 6, 1, 0.0F);
        this.setRotateAngle(earLeft, 0.0F, -0.3490658503988659F, 0.0F);
        this.maskLeft = new MowzieModelRenderer(this, 48, 18);
        this.maskLeft.setRotationPoint(0.0F, 0.0F, -1.0F);
        this.maskLeft.addBox(-7.0F, -8.0F, 0.0F, 7, 14, 2, 0.0F);
        this.setRotateAngle(maskLeft, 0.0F, 0.4363323129985824F, 0.0F);
        this.calfLeft = new MowzieModelRenderer(this, 12, 55);
        this.calfLeft.mirror = true;
        this.calfLeft.setRotationPoint(0.0F, 8.0F, 0.0F);
        this.calfLeft.addBox(-1.0F, 0.0F, -1.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(calfLeft, 1.3089969389957472F, 0.0F, 0.0F);
        this.handLeft = new MowzieModelRenderer(this, 0, 55);
        this.handLeft.mirror = true;
        this.handLeft.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.handLeft.addBox(-1.0F, 0.0F, -2.0F, 2, 5, 4, 0.0F);
        this.setRotateAngle(handLeft, 0.0F, 0.0F, 0.7853981633974483F);
        this.calfRight = new MowzieModelRenderer(this, 12, 55);
        this.calfRight.setRotationPoint(0.0F, 8.0F, 0.0F);
        this.calfRight.addBox(-1.0F, 0.0F, -1.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(calfRight, 1.3089969389957472F, 0.0F, 0.0F);
        this.shield = new MowzieModelRenderer(this, 66, 40);
        this.shield.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.shield.addBox(1.0F, -6.0F, -6.0F, 2, 12, 12, 0.0F);
        this.setRotateAngle(shield, 0.7853981633974483F, 0.0F, 0.0F);
        this.handRight = new MowzieModelRenderer(this, 0, 55);
        this.handRight.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.handRight.addBox(-1.0F, 0.0F, -2.0F, 2, 5, 4, 0.0F);
        this.setRotateAngle(handRight, 0.0F, 0.0F, -0.7853981633974483F);
        this.maskBase = new AdvancedModelRenderer(this, 0, 0);
        this.maskBase.setRotationPoint(0.0F, -3.0F, -8.0F);
        this.maskBase.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.neck = new MowzieModelRenderer(this, 49, 52);
        this.neck.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.neck.addBox(-1.5F, -9.0F, -1.5F, 3, 9, 3, 0.0F);
        this.setRotateAngle(neck, 0.3665191429188092F, 0.0F, 0.0F);
        this.modelCore = new MowzieModelRenderer(this, 0, 0);
        this.modelCore.setRotationPoint(0.0F, 24.0F, 0.0F);
        this.modelCore.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.head = new MowzieModelRenderer(this, 34, 34);
        this.head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head.addBox(-4.0F, -7.0F, -7.0F, 8, 8, 8, 0.0F);
        this.footRight = new MowzieModelRenderer(this, 21, 53);
        this.footRight.mirror = true;
        this.footRight.setRotationPoint(0.0F, 5.5F, 0.0F);
        this.footRight.addBox(-2.5F, 0.5F, -7.0F, 5, 2, 9, 0.0F);
        this.setRotateAngle(footRight, -0.5235987755982988F, 0.0F, 0.0F);
        this.armRightJoint = new MowzieModelRenderer(this, 0, 0);
        this.armRightJoint.setRotationPoint(-3.5F, -4.5F, 0.0F);
        this.armRightJoint.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(armRightJoint, 0.3490658503988659F, 0.3490658503988659F, 0.0F);
        this.earRight = new MowzieModelRenderer(this, 48, 0);
        this.earRight.mirror = true;
        this.earRight.setRotationPoint(-4.0F, -4.0F, -3.0F);
        this.earRight.addBox(-4.0F, -2.0F, 0.0F, 4, 6, 1, 0.0F);
        this.setRotateAngle(earRight, 0.0F, 0.3490658503988659F, 0.0F);
        this.shieldBase = new MowzieModelRenderer(this, 0, 0);
        this.shieldBase.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.shieldBase.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.armLeftJoint = new MowzieModelRenderer(this, 0, 0);
        this.armLeftJoint.setRotationPoint(3.5F, -4.5F, 0.0F);
        this.armLeftJoint.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(armLeftJoint, 0.3490658503988659F, -0.3490658503988659F, 0.0F);
        this.earringLeft = new MowzieModelRenderer(this, 0, 29);
        this.earringLeft.setRotationPoint(3.0F, 4.0F, 0.5F);
        this.earringLeft.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 0, 0.0F);
        this.armUpperRight = new MowzieModelRenderer(this, 41, 52);
        this.armUpperRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.armUpperRight.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2, 0.0F);
        this.setRotateAngle(armUpperRight, 0.0F, 0.0F, 0.9599310885968813F);
        this.headJoint = new MowzieModelRenderer(this, 0, 0);
        this.headJoint.setRotationPoint(0.0F, -7.0F, 1.0F);
        this.headJoint.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(headJoint, -0.3665191429188092F, 0.0F, 0.0F);
        this.chest = new MowzieModelRenderer(this, 0, 42);
        this.chest.setRotationPoint(0.0F, -4.0F, -3.0F);
        this.chest.addBox(-4.0F, -5.0F, -3.5F, 8, 5, 7, 0.0F);
        this.setRotateAngle(chest, -0.3490658503988659F, 0.0F, 0.0F);
        this.body = new AdvancedModelRenderer(this, 0, 24);
        this.body.setRotationPoint(0.0F, -13.0F, 2.0F);
        this.body.addBox(-5.5F, -6.0F, -8.0F, 11, 8, 10, 0.0F);
        this.maskRight = new MowzieModelRenderer(this, 48, 18);
        this.maskRight.mirror = true;
        this.maskRight.setRotationPoint(0.0F, 0.0F, -1.0F);
        this.maskRight.addBox(0.0F, -8.0F, 0.0F, 7, 14, 2, 0.0F);
        this.setRotateAngle(maskRight, 0.0F, -0.4363323129985824F, 0.0F);
        this.mane = new AdvancedModelRenderer(this, 0, 0);
        this.mane.setRotationPoint(0.0F, -2.0F, 4.0F);
        this.mane.addBox(-12.0F, -12.0F, 0.0F, 24, 24, 0, 0.0F);
        this.scaler = new MowzieModelRenderer(this, 0, 0);
        this.scaler.setRotationPoint(0.0F, 0, 0F);
        this.scaler.addBox(0, 0, 0, 0, 0, 0, 0.0F);
        this.flailer = new MowzieModelRenderer(this, 0, 0);
        this.flailer.setRotationPoint(0.0F, 0, 0F);
        this.flailer.addBox(0, 0, 0, 0, 0, 0, 0.0F);
        this.calfLeft.addChild(this.footLeft);
        this.body.addChild(this.thighLeftJoint);
        this.handRight.addChild(this.spearBase);
        this.body.addChild(this.loinClothBack);
        this.body.addChild(this.loinClothFront);
        this.body.addChild(this.thighRightJoint);
        thighRightJoint.addChild(thighRight);
        thighLeftJoint.addChild(thighLeft);
        this.armUpperLeft.addChild(this.armLowerLeft);
        this.armUpperRight.addChild(this.armLowerRight);
        this.earRight.addChild(this.earringRight);
        this.chest.addChild(this.neckJoint);
        this.armLeftJoint.addChild(this.armUpperLeft);
        this.spearBase.addChild(this.spear);
        this.head.addChild(this.earLeft);
        this.maskBase.addChild(this.maskLeft);
        this.thighLeft.addChild(this.calfLeft);
        this.armLowerLeft.addChild(this.handLeft);
        this.thighRight.addChild(this.calfRight);
        this.shieldBase.addChild(this.shield);
        this.armLowerRight.addChild(this.handRight);
        this.head.addChild(this.maskBase);
        this.neckJoint.addChild(this.neck);
        this.headJoint.addChild(this.head);
        this.calfRight.addChild(this.footRight);
        this.chest.addChild(this.armRightJoint);
        this.head.addChild(this.earRight);
        this.armLowerLeft.addChild(this.shieldBase);
        this.chest.addChild(this.armLeftJoint);
        this.earLeft.addChild(this.earringLeft);
        this.armRightJoint.addChild(this.armUpperRight);
        this.neck.addChild(this.headJoint);
        this.body.addChild(this.chest);
        this.modelCore.addChild(this.body);
        this.maskBase.addChild(this.maskRight);
        this.maskBase.addChild(this.mane);
        parts = new MowzieModelRenderer[]{modelCore, body, chest, thighLeft, thighRight, loinClothFront, loinClothBack, armRightJoint, armLeftJoint, neckJoint, armUpperRight, armLowerRight, handRight, spearBase, spear, armUpperLeft, armLowerLeft, handLeft, shieldBase, shield, neck, headJoint, head, maskBase, earLeft, earRight, maskLeft, maskRight, mane, earringLeft, earringRight, calfLeft, footLeft, calfRight, footRight, thighLeftJoint, thighRightJoint, scaler, flailer};
        setInitPose();
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
        GL11.glPushMatrix();
        if (entity instanceof EntityTribeElite) {
            GL11.glScalef(0.85f, 0.85f, 0.85f);
            GL11.glTranslatef(0, 0.25f, 0);
        } else {
            GL11.glScalef(0.75f, 0.75f, 0.75f);
            GL11.glTranslatef(0, 0.5f, 0);
        }
        this.modelCore.render(f5);
        GL11.glPopMatrix();
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }


    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        EntityTribesman tribesman = (EntityTribesman)entity;
        setToInitPose();
//                f = entity.ticksExisted;
//                f1 = 0.5f;
        float doWalk = tribesman.doWalk.getAnimationProgressSinSqrt();
        float dance = tribesman.dancing.getAnimationProgressSinSqrt();
        if (f1 > 0.55f) f1 = 0.55f;
        float globalSpeed = 1.5f;
        float globalHeight = 1 * doWalk;
        float globalDegree = 1 * doWalk * (1 - dance);
        faceTarget(neck, 2, f3, f4);
        faceTarget(head, 2, f3, f4);
        float frame = tribesman.frame + AnimationAPI.proxy.getPartialTick();

        if (tribesman instanceof EntityTribeElite)
        {
            armLeftJoint.rotateAngleX -= 0.2;
            armLeftJoint.rotateAngleY += 1.3;
            armLowerLeft.rotateAngleX -= 0.2;
            armLowerLeft.rotateAngleY += 0.2;
            armLowerLeft.rotateAngleZ += 1;
            spearBase.setScaleZ(1.5f);

            flap(armUpperLeft, 1 * globalSpeed, 0.1f * globalHeight, false, 0.5f, 0, f, f1);
            walk(armUpperLeft, 0.5f * globalSpeed, 0.3f * globalDegree, true, 0, 1, f, f1);
        }
        else {
            flap(armUpperLeft, 1 * globalSpeed, 0.3f * globalHeight, false, 0.5f, 0, f, f1);
            walk(armUpperLeft, 0.5f * globalSpeed, 0.7f * globalDegree, true, 0, 0, f, f1);
        }

        bob(body, 1 * globalSpeed, 2.5f * globalHeight, false, f, f1);
        walk(loinClothFront, 1 * globalSpeed, 0.5f * globalHeight, false, 2, 0, f, f1);
        walk(loinClothBack, 1 * globalSpeed, 0.5f * globalHeight, true, 2, 0, f, f1);
        walk(body, 1 * globalSpeed, 0.2f * globalHeight, false, 1, 0.2f * globalHeight, f, f1);
        walk(thighLeft, 1 * globalSpeed, 0.2f * globalHeight, true, 1, -0.4f * globalHeight, f, f1);
        walk(thighRight, 1 * globalSpeed, 0.2f * globalHeight, true, 1, -0.4f * globalHeight, f, f1);
        swing(body, 0.5f * globalSpeed, 0.7f * globalDegree, true, 0, 0, f, f1);
        swing(thighLeft, 0.5f * globalSpeed, 0.7f * globalDegree, false, 0, 0, f, f1);
        swing(thighRight, 0.5f * globalSpeed, 0.7f * globalDegree, false, 0, 0, f, f1);
        swing(chest, 0.5f * globalSpeed, 1.4f * globalDegree, false, 0, 0, f, f1);
        swing(neck, 0.5f * globalSpeed, 0.7f * globalDegree, true, 0, 0, f, f1);
        flap(modelCore, 0.5f * globalSpeed, 0.3f * globalHeight, false, 0, 0, f, f1);
        flap(neck, 0.5f * globalSpeed, 0.15f * globalHeight, true, 0, 0, f, f1);
        flap(head, 0.5f * globalSpeed, 0.15f * globalHeight, true, 0, 0, f, f1);
        walk(thighLeft, 0.5f * globalSpeed, 1.4f * globalDegree, false, 0, 1f * globalHeight, f, f1);
        walk(thighRight, 0.5f * globalSpeed, 1.4f * globalDegree, true, 0, 1f * globalHeight, f, f1);
        walk(calfLeft, 0.5f * globalSpeed, 1.2f * globalDegree, false, -1.5f, 0.3f * globalDegree, f, f1);
        walk(calfRight, 0.5f * globalSpeed, 1.2f * globalDegree, true, -1.5f, 0.3f * globalDegree, f, f1);
        walk(footLeft, 0.5f * globalSpeed, 1.2f * globalDegree, false, -3f, 0.15f * globalDegree, f, f1);
        walk(footRight, 0.5f * globalSpeed, 1.2f * globalDegree, true, -3f, 0.15f * globalDegree, f, f1);
        thighLeft.rotateAngleY += 1f * f1 * globalDegree;
        thighRight.rotateAngleY -= 1f * f1 * globalDegree;
        walk(neck, 1 * globalSpeed, 0.2f * globalHeight, true, 0.5f, 0.5f * globalDegree, f, f1);
        walk(head, 1 * globalSpeed, 0f * globalHeight, true, 0.5f, -0.5f * globalDegree, f, f1);
        flap(armUpperRight, 1 * globalSpeed, 0.3f * globalHeight, true, 0.5f, 0, f, f1);
        walk(armUpperRight, 0.5f * globalSpeed, 0.7f * globalDegree, false, 0, 0, f, f1);
        walk(armLowerRight, 0.5f * globalSpeed, 1 * globalDegree, false, -1, 0, f, f1);
        walk(armLowerLeft, 0.5f * globalSpeed, 1 * globalDegree, true, -1, 0, f, f1);
        walk(handRight, 0.5f * globalSpeed, 1 * globalDegree, false, -2, 0.8f * globalDegree, f, f1);
        swing(handRight, 0.5f * globalSpeed, 1f * globalDegree, true, 0, 0, f, f1);
        walk(handLeft, 0.5f * globalSpeed, 1 * globalDegree, true, -2, 0.4f * globalDegree, f, f1);

        if (tribesman.getAnimID() != -2) {
            walk(body, 0.2f, 0.05f, false, 0, 0, frame, 1f);
            walk(thighLeftJoint, 0.2f, 0.05f, true, 0, 0, frame, 1f);
            walk(thighRightJoint, 0.2f, 0.05f, true, 0, 0, frame, 1f);
            walk(neck, 0.2f, 0.02f, true, 1f, 0, frame, 1f);
            walk(head, 0.2f, 0.02f, true, 1f, 0, frame, 1f);
            flap(armUpperLeft, 0.2f, -0.1f, true, -1, 0, frame, 1F);
            flap(armUpperRight, 0.2f, 0.1f, true, -1, 0, frame, 1F);
        }

        //Dancing
        float danceSpeed = 1.2f;
        thighLeft.rotateAngleY -= 0.6f * dance;
        thighRight.rotateAngleY += 0.6f * dance;
        bob(modelCore, 0.3f * danceSpeed, 10f * dance, true, frame, 1f);
        flap(modelCore, 0.3f * danceSpeed, 0.5f * dance, false, 0, 0, frame, 1f);
        walk(thighLeft, 0.3f * danceSpeed, 0.6f * dance, false, 0, -0.6f * dance, frame, 1f);
        walk(calfLeft, 0.3f * danceSpeed, 0.5f * dance, true, 0, 0.6f * dance, frame, 1f);
        walk(footLeft, 0.3f * danceSpeed, 0.2f * dance, true, 0, -0.5f * dance, frame, 1f);
        walk(thighRight, 0.3f * danceSpeed, 0.6f * dance, true, 0, -0.6f * dance, frame, 1f);
        walk(calfRight, 0.3f * danceSpeed, 0.5f * dance, false, 0, 0.6f * dance, frame, 1f);
        walk(footRight, 0.3f * danceSpeed, 0.2f * dance, false, 0, -0.5f * dance, frame, 1f);
        armRightJoint.rotateAngleX -= 1.7 * dance;
        handRight.rotateAngleX += 1 * dance;
        walk(armUpperRight, 1.2f * danceSpeed, 0.5f * dance, false, 0, -0.3f * dance, frame, 1f);
        walk(armLowerRight, 1.2f * danceSpeed, 0.5f * dance, true, 0, 0, frame, 1f);
        armLeftJoint.rotateAngleX -= 1.7 * dance;
        walk(armUpperLeft, 1.2f * danceSpeed, 0.5f * dance, false, 0, -0.3f * dance, frame, 1f);
        walk(armLowerLeft, 1.2f * danceSpeed, 0.5f * dance, true, 0, 0, frame, 1f);
        flap(neck, 0.3f * danceSpeed, 0.2f * dance, true, 0, 0, frame, 1f);
        flap(head, 1.2f * danceSpeed, 0.2f * dance, true, 0, 0, frame, 1f);
        walk(loinClothFront, 0.6f * danceSpeed, 0.6f * dance, true, 1, -0.4f, frame, 1f);
        walk(loinClothBack, 0.6f * danceSpeed, 0.6f * dance, false, 1, 0.4f, frame, 1f);
        if (tribesman instanceof EntityTribeElite) {
            armLeftJoint.rotateAngleX += 0.2 * dance;
            armLeftJoint.rotateAngleY -= 1.3 * dance;
            armLowerLeft.rotateAngleX += 0.2 * dance;
            armLowerLeft.rotateAngleY -= 0.2 * dance;
            armLowerLeft.rotateAngleZ -= 1 * dance;
        }
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        EntityTribesman tribesman = (EntityTribesman) entity;
        animator.update(tribesman);
        setRotationAngles(f, f1, f2, f3, f4, f5, tribesman);

        float frame = tribesman.frame + AnimationAPI.proxy.getPartialTick();

        if (entity instanceof EntityTribeElite) {
            animator.setAnim(1);
            animator.setStationaryPhase(3);
            animator.startPhase(4);
            animator.rotate(body, -0.3f, 1f, 0);
            animator.move(modelCore, -4, 0, -2);
            animator.rotate(chest, 0, 0.2f, 0);
            animator.rotate(neck, 0.1f, -0.6f, 0);
            animator.rotate(head, 0.1f, -0.6f, 0);
            animator.rotate(armUpperLeft, 0, 0, -0.5f);
            animator.rotate(armLeftJoint, 0.2f, -1.3f, 0);
            animator.rotate(armLowerLeft, 0.2f, -0.2f, -1);
            animator.rotate(armUpperRight, 0, 0.5f, 0);
            animator.rotate(armLowerRight, -1, -0.5f, 0);
            animator.rotate(handRight, 1f, 0, 0);
            animator.rotate(thighLeft, -0.9f, 0.3f, 0);
            animator.rotate(calfLeft, 0.1f, 0, 0);
            animator.rotate(footLeft, 0, 0, 0);
            animator.rotate(thighRight, 0.3f, -0.9f, 0);
            animator.rotate(calfRight, 0, 0, 0);
            animator.rotate(footRight, 0, 0, 0);
            animator.endPhase();
            animator.setStationaryPhase(1);
            animator.startPhase(3);
            animator.rotate(body, 0.5f, -0.3f, 0);
            animator.move(modelCore, -1.5f, 1.2f, -8.5f);
            animator.rotate(chest, 0, -0.5f, 0);
            animator.rotate(neck, -0.1f, 0.3f, 0);
            animator.rotate(head, -0.2f, 0.3f, 0);
            animator.rotate(armLeftJoint, 0.2f, -1.3f, 0);
            animator.rotate(armLowerLeft, 0.2f, -0.2f, -1);
            animator.rotate(armUpperRight, -1.7f, 0, -0.5f);
            animator.rotate(armLowerRight, 0.7f, 0, 0);
            animator.rotate(handRight, 1.4f, 0.8f, 0.7f);
            animator.rotate(thighLeft, -0.8f, 0.7f, 0);
            animator.rotate(calfLeft, -0.6f, 0, 0);
            animator.rotate(footLeft, 0.9f, 0, 0);
            animator.move(thighRight, 0, 1, 0);
            animator.rotate(thighRight, 0.7f, 0, 0f);
            animator.rotate(calfRight, -0.5f, 0, 0);
            animator.rotate(footRight, -0.5f, 0, 0);
            animator.endPhase();
            animator.setStationaryPhase(1);
            animator.resetPhase(6);

            animator.setAnim(-3);
            animator.startPhase(3);
            animator.rotate(armLeftJoint, 0.2f, -1.3f, 0);
            animator.rotate(armLowerLeft, 0.2f, -0.2f, -1);
            animator.move(body, 0, 5f, 1f);
            animator.rotate(body, 0.3f, 0, 0);
            animator.rotate(thighLeftJoint, -0.3f, 0, 0);
            animator.rotate(thighRightJoint, -0.3f, 0, 0);
            animator.rotate(thighLeft, -0.5f, 0, 0);
            animator.rotate(thighRight, -0.5f, 0, 0);
            animator.rotate(calfLeft, 0.8f, 0, 0);
            animator.rotate(calfRight, 0.8f, 0, 0);
            animator.rotate(footLeft, -0.3f, 0, 0);
            animator.rotate(footRight, -0.3f, 0, 0);
            animator.rotate(neck, 0.5f, 0, 0);
            animator.rotate(head, -0.3f, 0, 0);
            animator.rotate(armUpperLeft, -0.3f, 0, -1);
            animator.rotate(armUpperRight, -0.3f, 0, 1);
            animator.rotate(armLowerLeft, -0.7f, 0, 0);
            animator.rotate(armLowerRight, -0.7f, 0, 0);
            animator.endPhase();
            animator.resetPhase(7);

            animator.setAnim(-2);
            animator.startPhase(3);
            animator.rotate(armLeftJoint, 0.2f, -1.3f, 0);
            animator.rotate(armLowerLeft, 0.2f, -0.2f, -1);
            animator.move(body, 0, 5f, 1f);
            animator.rotate(body, 0.3f, 0, 0);
            animator.rotate(thighLeftJoint, -0.3f, 0, 0);
            animator.rotate(thighRightJoint, -0.3f, 0, 0);
            animator.rotate(thighLeft, -0.5f, 0, 0);
            animator.rotate(thighRight, -0.5f, 0, 0);
            animator.rotate(calfLeft, 0.8f, 0, 0);
            animator.rotate(calfRight, 0.8f, 0, 0);
            animator.rotate(footLeft, -0.3f, 0, 0);
            animator.rotate(footRight, -0.3f, 0, 0);
            animator.rotate(neck, 0.5f, 0, 0);
            animator.rotate(head, -0.3f, 0, 0);
            animator.rotate(armUpperLeft, -0.3f, 0, -1);
            animator.rotate(armUpperRight, -0.3f, 0, 1);
            animator.rotate(armLowerLeft, -0.7f, 0, 0);
            animator.rotate(armLowerRight, -0.7f, 0, 0);
            animator.endPhase();
            animator.resetPhase(5);
            animator.startPhase(5);
            animator.rotate(head, -0.8f, 0, 0);
            animator.move(flailer, 1, 0, 0);
            animator.endPhase();
            animator.setStationaryPhase(10);
            animator.startPhase(10);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -0.8f, 0, 0);
            animator.move(body, 0, -22f, -5f);
            animator.endPhase();
            animator.startPhase(4);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -0.8f, 0, 0);
            animator.move(body, 0, 7, 0);
            animator.endPhase();
            animator.startPhase(2);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -1.6f, 0, 0);
            animator.move(body, 0, -3, 5);
            animator.endPhase();
            animator.startPhase(2);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -1.58f, 0, 0);
            animator.move(body, 0, 9f, 5);
            animator.endPhase();
            animator.setStationaryPhase(15);

            armLeftJoint.rotateAngleX += 0.2 * flailer.rotationPointX;
            armLeftJoint.rotateAngleY -= 1.3 * flailer.rotationPointX;
            armLowerLeft.rotateAngleX += 0.2 * flailer.rotationPointX;
            armLowerLeft.rotateAngleY -= 0.2 * flailer.rotationPointX;
            armLowerLeft.rotateAngleZ -= 1 * flailer.rotationPointX;
        }
        else {
            animator.setAnim(1);
            animator.setStationaryPhase(3);
            animator.startPhase(4);
            animator.rotate(body, -0.3f, 1f, 0);
            animator.move(modelCore, -4, 0, -2);
            animator.rotate(chest, 0, 0.2f, 0);
            animator.rotate(neck, 0.1f, -0.6f, 0);
            animator.rotate(head, 0.1f, -0.6f, 0);
            animator.rotate(armUpperLeft, 0, 0, -0.5f);
            animator.rotate(armUpperRight, -2, 0, -1.5f);
            animator.rotate(armLowerRight, -0.5f, 0, 0);
            animator.rotate(handRight, 0, 1f, 0);
            animator.rotate(thighLeft, -0.9f, 0.3f, 0);
            animator.rotate(calfLeft, 0.1f, 0, 0);
            animator.rotate(footLeft, 0, 0, 0);
            animator.rotate(thighRight, 0.3f, -0.9f, 0);
            animator.rotate(calfRight, 0, 0, 0);
            animator.rotate(footRight, 0, 0, 0);
            animator.endPhase();
            animator.setStationaryPhase(1);
            animator.startPhase(3);
            animator.rotate(body, 0.5f, -0.3f, 0);
            animator.move(modelCore, -1.5f, 1.2f, -8.5f);
            animator.rotate(chest, 0, -0.5f, 0);
            animator.rotate(neck, -0.1f, 0.3f, 0);
            animator.rotate(head, -0.2f, 0.3f, 0);
            animator.rotate(armUpperRight, -0.8f, 0, -0.5f);
            animator.rotate(armLowerRight, 0.7f, 0, 0);
            animator.rotate(handRight, 0.6f, 0.6f, 0);
            animator.rotate(thighLeft, -0.8f, 0.7f, 0);
            animator.rotate(calfLeft, -0.6f, 0, 0);
            animator.rotate(footLeft, 0.9f, 0, 0);
            animator.move(thighRight, 0, 1, 0);
            animator.rotate(thighRight, 0.7f, 0, 0f);
            animator.rotate(calfRight, -0.5f, 0, 0);
            animator.rotate(footRight, -0.5f, 0, 0);
            animator.endPhase();
            animator.setStationaryPhase(1);
            animator.resetPhase(6);

            animator.setAnim(-3);
            animator.startPhase(3);
            animator.move(body, 0, 5f, 1f);
            animator.rotate(body, 0.3f, 0, 0);
            animator.rotate(thighLeftJoint, -0.3f, 0, 0);
            animator.rotate(thighRightJoint, -0.3f, 0, 0);
            animator.rotate(thighLeft, -0.5f, 0, 0);
            animator.rotate(thighRight, -0.5f, 0, 0);
            animator.rotate(calfLeft, 0.8f, 0, 0);
            animator.rotate(calfRight, 0.8f, 0, 0);
            animator.rotate(footLeft, -0.3f, 0, 0);
            animator.rotate(footRight, -0.3f, 0, 0);
            animator.rotate(neck, 0.5f, 0, 0);
            animator.rotate(head, -0.3f, 0, 0);
            animator.rotate(armUpperLeft, -0.3f, 0, -1);
            animator.rotate(armUpperRight, -0.3f, 0, 1);
            animator.rotate(armLowerLeft, -0.7f, 0, 0);
            animator.rotate(armLowerRight, -0.7f, 0, 0);
            animator.endPhase();
            animator.resetPhase(7);

            animator.setAnim(-2);
            animator.startPhase(3);
            animator.rotate(armLeftJoint, 0.2f, -1.3f, 0);
            animator.rotate(armLowerLeft, 0.2f, -0.2f, -1);
            animator.move(body, 0, 5f, 1f);
            animator.rotate(body, 0.3f, 0, 0);
            animator.rotate(thighLeftJoint, -0.3f, 0, 0);
            animator.rotate(thighRightJoint, -0.3f, 0, 0);
            animator.rotate(thighLeft, -0.5f, 0, 0);
            animator.rotate(thighRight, -0.5f, 0, 0);
            animator.rotate(calfLeft, 0.8f, 0, 0);
            animator.rotate(calfRight, 0.8f, 0, 0);
            animator.rotate(footLeft, -0.3f, 0, 0);
            animator.rotate(footRight, -0.3f, 0, 0);
            animator.rotate(neck, 0.5f, 0, 0);
            animator.rotate(head, -0.3f, 0, 0);
            animator.rotate(armUpperLeft, -0.3f, 0, -1);
            animator.rotate(armUpperRight, -0.3f, 0, 1);
            animator.rotate(armLowerLeft, -0.7f, 0, 0);
            animator.rotate(armLowerRight, -0.7f, 0, 0);
            animator.endPhase();
            animator.resetPhase(5);
            animator.startPhase(5);
            animator.rotate(head, -0.8f, 0, 0);
            animator.move(flailer, 1, 0, 0);
            animator.endPhase();
            animator.setStationaryPhase(10);
            animator.startPhase(10);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -0.8f, 0, 0);
            animator.move(body, 0, -22f, -5f);
            animator.endPhase();
            animator.startPhase(4);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -0.8f, 0, 0);
            animator.move(body, 0, 7, 0);
            animator.endPhase();
            animator.startPhase(2);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -1.6f, 0, 0);
            animator.move(body, 0, -3, 5);
            animator.endPhase();
            animator.startPhase(2);
            animator.move(scaler, 0.999f, 0, 0);
            animator.rotate(head, -1.58f, 0, 0);
            animator.move(body, 0, 9f, 5);
            animator.endPhase();
            animator.setStationaryPhase(15);
        }
        float flailSpeed = 2f;
        bob(modelCore, 0.3f * flailSpeed, 10f * flailer.rotationPointX, true, frame, 1f);
        walk(thighLeft, 0.3f * flailSpeed, 0.6f * flailer.rotationPointX, false, 0, -0.3f * flailer.rotationPointX, frame, 1f);
        walk(calfLeft, 0.3f * flailSpeed, 0.5f * flailer.rotationPointX, true, 0, 0.3f * flailer.rotationPointX, frame, 1f);
        walk(footLeft, 0.3f * flailSpeed, 0.2f * flailer.rotationPointX, true, 0, 0, frame, 1f);
        walk(thighRight, 0.3f * flailSpeed, 0.6f * flailer.rotationPointX, true, 0, -0.3f * flailer.rotationPointX, frame, 1f);
        walk(calfRight, 0.3f * flailSpeed, 0.5f * flailer.rotationPointX, false, 0, 0.3f * flailer.rotationPointX, frame, 1f);
        walk(footRight, 0.3f * flailSpeed, 0.2f * flailer.rotationPointX, false, 0, 0, frame, 1f);
        armRightJoint.rotateAngleX -= 1.7 * flailer.rotationPointX;
        handRight.rotateAngleX += 1 * flailer.rotationPointX;
        walk(armUpperRight, 0.6f * flailSpeed, 0.5f * flailer.rotationPointX, false, 0, -0.3f * flailer.rotationPointX, frame, 1f);
        walk(armLowerRight, 0.6f * flailSpeed, 0.5f * flailer.rotationPointX, true, 0, 0, frame, 1f);
        armLeftJoint.rotateAngleX -= 1.7 * flailer.rotationPointX;
        walk(armUpperLeft, 0.6f * flailSpeed, 0.5f * flailer.rotationPointX, false, 0, -0.3f * flailer.rotationPointX, frame, 1f);
        walk(armLowerLeft, 0.6f * flailSpeed, 0.5f * flailer.rotationPointX, true, 0, 0, frame, 1f);

        float scale = 1 - scaler.rotationPointX;
        body.setScaleX(scale);
        body.setScaleY(scale);
        body.setScaleZ(scale);
        maskBase.setScaleX(1/scale);
        maskBase.setScaleY(1/scale);
        maskBase.setScaleZ(1/scale);
    }
}

